version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: d384d0cb-ef68-40dd-a4c5-a70894e3e94f